dataset_defaults = {
    'Airfoil': {
        'input_dim': 5,
        'metrics': 'rmse',
        'is_ood': 0,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.975,
            'batch_selection': 'knn',
            'lr': 1e-2,
            'foma_input': 0,
            'foma_latent': 1,
            'alpha': 1.4,
            'batch_size': 32,
            'num_epochs': 100,
            'small_singular': 0,
        },
    },
    'NO2': {
        'input_dim': 7,
        'metrics': 'rmse',
        'is_ood': 0,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.95,
            'batch_selection': 'knnp',
            'lr': 1e-3,
            'foma_input': 0,
            'foma_latent': 1,
            'alpha': 0.3,
            'batch_size': 8,
            'num_epochs': 250,
            'small_singular': 1,
        },
    },
    'TimeSeries-exchange_rate': {
        'metrics': 'rmse',
        'is_ood': 0,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # ts
        'hidCNN': 50,
        'hidRNN': 50,
        'window': 24*7,
        'CNN_kernel': 6,
        'highway_window': 24,
        'clip': 10.,
        'dropout': 0.2,
        'horizon': 12,
        'skip': 24,
        'hidSkip': 5,
        'L1Loss': False,
        'normalize': 2,
        'output_fun': None,
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.95,
            'batch_selection': 'knn',
            'lr': 1e-3,
            'foma_input': 1,
            'foma_latent': 0,
            'alpha': 1,
            'batch_size': 8,
            'num_epochs': 150,
            'small_singular': 0,
        },
    },
    'TimeSeries-electricity': {
        'metrics': 'rmse',
        'is_ood': 0,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # ts
        'hidCNN': 100,
        'hidRNN': 100,
        'window': 24*7,
        'CNN_kernel': 6,
        'highway_window': 24,
        'clip': 10.,
        'dropout': 0.2,
        'horizon': 24,
        'skip': 24,
        'hidSkip': 5,
        'L1Loss': False,
        'normalize': 2,
        'output_fun': 'Linear',
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.875,
            'batch_selection': 'knn',
            'lr': 1e-3,
            'foma_input': 1,
            'foma_latent': 0,
            'alpha': 1,
            'batch_size': 8,
            'num_epochs': 200,
            'small_singular': 0,
        },
    },
    'RCF_MNIST': {
        'metrics': 'rmse',
        'is_ood': 1,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # rcf
        'use_rotate_class': 0,
        'spurious_ratio': 0.8,
        'construct_color_data': -1,
        'construct_no_color_data': 0,
        'vis_rcf': 0,
        'all_pos_color': 0,
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.85,
            'batch_selection': 'knnp',
            'lr': 1e-4,
            'foma_input': 1,
            'foma_latent': 1,
            'alpha': 0.4,
            'batch_size': 128,
            'num_epochs': 50,
            'small_singular': 1,
        },
    },
    'CommunitiesAndCrime': {
        'input_dim': 122,
        'metrics': 'rmse',
        'is_ood': 1,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.875,
            'batch_selection': 'knn',
            'lr': 1e-3,
            'foma_input': 1,
            'foma_latent': 1,
            'alpha': 0.6,
            'batch_size': 64,
            'num_epochs': 100,
            'small_singular': 1,
        },
    },
    'Dti_dg': {
        'metrics': 'r',
        'is_ood': 1,
        # split
        'train_ratio': 0.7,
        'valid_ratio': 0.1,
        'id_train_val_split': [0.7, 0.1, 0.2],
        # dti
        'read_dataset': 1,
        'sub_sample_batch_max_num': 100,
        'store_log': 0,
        'task': 'domain_generalization',
        'algorithm': 'ERM',
        'hparams': '',
        'hparams_seed': 0,
        'trial_seed': 0,
        'test_envs': [6, 7, 8],
        'output_dir': 'train_output',
        'holdout_fraction': 0.2,
        'uda_holdout_fraction': 0.,
        # command arguments
        'command_args': {
            'estimate_id': 0,
            'rho': 0.825,
            'batch_selection': 'knn',
            'lr': 1e-2,
            'foma_input': 0,
            'foma_latent': 1,
            'alpha': 0.6,
            'batch_size': 64,
            'num_epochs': 250,
            'small_singular': 0,
        },
    },
}
